---
- hosts: vbn
  become: yes
  tasks: 
	 - name: install vsftpd ubuntu
	   apt: name= vsftpd update-cache=yes state=latest
	   ignore_errors: yes
	   notify: start vsftpd 

	 - name: install vsftpd centos
	   yum: name= vsftpd state=latest
	   ignore_errors: yes
	   notify: start vsftpd 
	   
	   Handlers: 
	   	   - name: start vsftpd 
	             service: name=vsftpd enabled=yes state=started